name: Build Low Code
on:
  #监听push操作
  push:
    branches:
      # mian分支，你也可以改成其他分支
      - main
jobs:
  # 任务ID
  build:
    # 运行环境
    runs-on: ubuntu-latest
    # 步骤
    steps:
    - uses: actions/checkout@v2
    - name: Install pnpm
      uses: pnpm/action-setup@v2.2.2
      with:
        version: next-7
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 16.15.0
        cache: 'pnpm'
    - name: Install
      # 步骤执行指令
      run: pnpm i
    - name: Build
      run: pnpm build
    # 命名这个任务为发布Deploy
    - name: Deploy
      # 因为构建之后，需要把代码上传到服务器上，所以需要连接到ssh，并且做一个拷贝操作
      uses: cross-the-world/scp-pipeline@master
      env:
        WELCOME: "ssh scp ssh pipelines"
        LASTSSH: "Doing something after copying"
      with:
        host: ${{ secrets.USER_HOST }}
        user: ${{ secrets.USER_NAME }}
        pass: ${{ secrets.USER_PASS }}
        connect_timeout: 10s
        local: './dist/*'
        remote: /www/wwwroot/lowcode
